/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/babylonjs/one/BasicVIew/': RouteRecordInfo<'/babylonjs/one/BasicVIew/', '/babylonjs/one/BasicVIew', Record<never, never>, Record<never, never>>,
    '/babylonjs/one/ImportModel/': RouteRecordInfo<'/babylonjs/one/ImportModel/', '/babylonjs/one/ImportModel', Record<never, never>, Record<never, never>>,
    '/babylonjs/one/ParentChildren.vue/': RouteRecordInfo<'/babylonjs/one/ParentChildren.vue/', '/babylonjs/one/ParentChildren/vue', Record<never, never>, Record<never, never>>,
    '/babylonjs/one/Village/': RouteRecordInfo<'/babylonjs/one/Village/', '/babylonjs/one/Village', Record<never, never>, Record<never, never>>,
    '/viewDemo/one/oneFirstView/': RouteRecordInfo<'/viewDemo/one/oneFirstView/', '/viewDemo/one/oneFirstView', Record<never, never>, Record<never, never>>,
  }
}
